name: CD

on:
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    create-version-pr-or-release:
        name: "Create Version PR/Release"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node Environment
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: "npm"
            - name: Install Dependencies
              run: npm ci
            - name: Create Version PR or Github Release
              id: changesets
              uses: changesets/action@v1
              with:
                publish: npx changeset tag
              env:
                GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
            - name: Print Outputs
              run: echo '${{ toJson(steps.changesets.outputs )}}'
            - name: Send A Slack Message For Version PR Updates
              if: steps.changesets.outputs.pullRequestNumber
              uses: slackapi/slack-github-action@v1.24.0
              with:
               payload: |
                {
                    "blocks": [
                    {
                        "type": "section",
                        "text": {
                        "type": "mrkdwn",
                        "text": "* <https://github.com/${{github.repository}}/pull/${{steps.changesets.outputs.pullRequestNumber}}|Version Pull Request>* was updated. Review it and merge it to create a new release and deployment."
                        }
                    }
                    ]
                }
              env:
               SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
               SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
